#!/usr/bin/env bash

IS_ZSH_SETUP=$(cat ~/.zshrc | grep "ADDED BY MACOS-SETUP" >> /dev/null ; echo $?)
if [ $IS_ZSH_SETUP ]; then
    echo "ZSH is already set up" && exit 0
fi

cp ~/.zshrc ~/.zshrc.backup
cat <<EOF >> ~/.zshrc
# ADDED BY MACOS-SETUP
eval "$(pyenv init --path)"

alias ll="ls -al"
alias t=terraform
alias tp="terraform plan"
alias ta="terraform apply"
alias taaa="terraform apply --auto-approve"
alias tws="terraform workspace select"
alias twl="terraform workspace list"
alias k=kubectl
alias gpl="git pull -r"
alias gp="git push"
alias gh=git
export d="--dry-run=client"
export do="-o yaml $d"
wttr() {
  while true; do clear && curl wttr.in/BD18%204LB && echo "Refreshed at: $(date "+%H:%M")"; sleep 7200; done
}

source <(kubectl completion zsh)

[[ /usr/local/bin/kubectl ]] && source <(kubectl completion zsh)
EOF